name: gardenmarketingdigital
favicon: null
layout_spectrum: 0
typography_spectrum: 0.50872
title: Garden Marketing Digital
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#33ba7c'
    - '#4fc48f'
    - '#49be88'
    - '#33b278'
    - '#40b580'
  brandStrength: 0.375
  lightness: 0.23061657417565584
  saturation: 0.9292728833388537
  rhythmicContrast: 0.4369198936037719
purpose: []
