name: Garden Marketing Digital
favicon: null
layout_spectrum: 0.99133
typography_spectrum: 0.23934
title: Pagina Inicial
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#33ba7c'
    - '#4fc48f'
    - '#49be88'
    - '#33b278'
    - '#40b580'
  brandStrength: 0
  lightness: 0.375
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
