typography_spectrum: 0.2629433732945472
color:
  brandColors:
    - '#F4F4F2'
    - '#3CA77B'
    - '#80C4A7'
    - '#BDDDCE'
    - '#626A69'
  brandStrength: 0.9108269046992064
  lightness: 0.019510004902258515
  saturation: 0.8487992258742452
  rhythmicContrast: 0.6061360139865428
opengraph:
  image: null
  type: 'https://www.facebook.com/gardendigital/'
  appId: null
layout_spectrum: 0.4088331644888967
analytics:
  google: UA-74404799-1
  facebook: null
  twitter: null
author:
  name: Garden Marketing Digital
  email: salmo@gardendigital.com.br
  url: www.gardendigital.com.br
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/b9afcec4-6f45-4d3d-b6e7-39bee919c532.png
name: Marketing Digital
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: O negócio
    id: c0f23c75-912d-48c3-8f36-02a3d261e320
    type: content
  - name: Quem somos
    id: f95dfde5-7c0b-4cb5-abe3-c4de6a2a1793
    type: content
  - name: Diagnóstico de Mkt Digital
    id: ee642526-c816-450d-a347-f7f4980c3fa6
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/d56d0ec0-2ad8-4f68-841f-0281a629569b.png
title: Garden Digital
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/9ecd4e8f-7f31-4903-aca5-1d83e75e75f2.png">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/9ecd4e8f-7f31-4903-aca5-1d83e75e75f2.png
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: Marketing Digital
purpose:
  - type: contact
    url: 'mailto:E-mail'
    label: Entre em Contato
github: true
