name: Garden Marketing Digital
favicon: null
layout_spectrum: 0.74855
typography_spectrum: 0.49037
title: Garden Marketing Digital
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00ab7a'
    - '#198b6a'
    - '#fdfbfb'
    - '#94c9ba'
    - '#68b59f'
  brandStrength: 0.8125
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0.25
purpose: []
