name: Garden Marketing Digital
favicon: null
layout_spectrum: 0.74709
typography_spectrum: 0.31835
title: Garden Marketing Digital
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-74404799-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3ca77b'
    - '#80cfaf'
    - '#ffffff'
    - '#343f3d'
    - '#00ffff'
  brandStrength: 0.5
  lightness: 0.3125
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
