name: Garden Marketing Digital
favicon: null
layout_spectrum: 1
typography_spectrum: 0.37402
title: Garden Marketing Digital
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-74404799-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00ab7a'
    - '#198b6a'
    - '#fdfbfb'
    - '#94c9ba'
    - '#68b59f'
  brandStrength: 0.5
  lightness: 0.3125
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
