name: Garden Marketing Digital
favicon: null
layout_spectrum: 0.74709
typography_spectrum: 0.49037
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7496b1'
    - '#2d587b'
    - '#a1bdd2'
    - '#fefefe'
    - '#36b881'
  brandStrength: 0.0625
  lightness: 0.25
  saturation: 0.1875
  rhythmicContrast: 0.25
purpose: []
